DjangoUnlimited/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from rest_framework import routers

from Admin.views import download_file

router = routers.SimpleRouter()

urlpatterns = [
    path('', include('Home.urls')),
    path('admin/backups/', include('dbbackup_ui.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('Accounts.urls')),
    path('alumni/', include('Alumni.urls')),
    path('my_admin/', include('Admin.urls')),
    path('student/', include('Student.urls')),
    path('employer/', include('Employer.urls')),
    path('HelpDesk/', include('HelpDesk.urls')),
    path('bulletin/', include('Bulletin.urls')),  # Using URLS from the Bulletin app
    path('backup/<str:filename>', download_file, name="backup_download"),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
                            static(settings.BACKUP_URL, document_root=settings.BACKUP_ROOT)

Home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('create_job', views.create_job, name='create_job'),
    path('view_jobs', views.view_jobs, name='view_jobs'),
    path('my_applications', views.my_applications, name='my_applications'),
    path('job_details/<int:id>', views.job_details, name='job_details'),
    path('edit_job/<int:id>', views.edit_job, name='edit_job'),
    path('delete_job/<int:id>', views.delete_job, name='delete_job'),
    path('close_job/<int:id>', views.close_job, name='close_job'),
    path('reopen_job/<int:id>', views.reopen_job, name='reopen_job'),
    path('view_students', views.view_students, name='view_students'),
    path('view_alumni', views.view_alumni, name='view_alumni'),
    path('student_details/<int:id>', views.student_details, name='student_details'),
    path('alumni_details/<int:id>', views.alumni_details, name='alumni_details'),
    path('job_to_student_skills/<int:id>', views.job_to_student_skills, name='job_to_student_skills'),
    path('job_to_alumni_skills/<int:id>', views.job_to_alumni_skills, name='job_to_alumni_skills'),
    path('get_job_description_file/<int:id>', views.get_job_description_file, name='get_job_description_file'),
    path('get_student_cv_file/<int:id>', views.get_student_cv_file, name='get_student_cv_file'),
    path('get_alumni_cv_file/<int:id>', views.get_alumni_cv_file, name='get_alumni_cv_file'),
    path('terms', views.terms, name='terms'),
    path('faq', views.faq, name='faq'),
    path('anti_scam', views.anti_scam, name='anti_scam'),
    path('privacy', views.privacy, name='privacy'),
    path('sitemap', views.sitemap, name='sitemap'),
]

Home/models.py
import os

from django.core.exceptions import SuspiciousFileOperation
from django.core.files.storage import FileSystemStorage
from django.core.mail import EmailMessage
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
import threading

# Create your models here.
from Admin.models import Admin

from DjangoUnlimited.settings import EMAIL_HOST_USER
from Employer.models import Employer


class OverwriteStorage(FileSystemStorage):
    def get_available_name(self, name, max_length=None):
        dir_name, file_name = os.path.split(name)
        file_root, file_ext = os.path.splitext(file_name)

        while self.exists(name) or (max_length and len(name) > max_length):
            date = datetime.now().strftime("%d-%m-%Y_%H-%M-%S")
            name = os.path.join(dir_name, "%s_%s%s" % (file_root, date, file_ext))
            if max_length is None:
                continue
            truncation = len(name) - max_length
            if truncation > 0:
                file_root = file_root[:-truncation]
                if not file_root:
                    raise SuspiciousFileOperation(
                        'Storage can not find an available filename for "%s". '
                        'Please make sure that the corresponding file field '
                        'allows sufficient "max_length".' % name
                    )
                name = os.path.join(dir_name, "%s_%s%s" % (file_root, date, file_ext))
        return name

class Industry(models.Model):
    industry_name = models.CharField(max_length=50, unique=True)

    def clean(self):
        self.industry_name = self.industry_name.capitalize()

    def __str__(self):
        name = self.industry_name
        return name

    class Meta:
        verbose_name_plural = 'Industries'


class Skill(models.Model):
    skill_name = models.CharField(max_length=50, unique=True)

    def clean(self):
        self.skill_name = self.skill_name.capitalize()

    def __str__(self):
        name = self.skill_name
        return name


class Major(models.Model):
    major_name = models.CharField(max_length=50, unique=True)

    def clean(self):
        self.major_name = self.major_name.capitalize()

    def __str__(self):
        name = self.major_name
        return name


class JobType(models.Model):
    type_name = models.CharField(max_length=50, unique=True)

    def clean(self):
        self.type_name = self.type_name.capitalize()

    def __str__(self):
        name = self.type_name
        return name


class Job(models.Model):
    LOCATION_CHOICES = [
        ('Abu Dhabi', 'Abu Dhabi'),
        ('Dubai', 'Dubai'),
        ('Sharjah', 'Sharjah'),
        ('Umm al-Qaiwain', 'Umm al-Qaiwain'),
        ('Fujairah', 'Fujairah'),
        ('Ajman', 'Ajman'),
        ('Ra’s al-Khaimah', 'Ra’s al-Khaimah'),
        ('Remote', 'Remote'),
    ]
    STATUS_CHOICES = [
        ('Accepted', 'Accepted'),
        ('Rejected', 'Rejected'),
        ('Pending', 'Pending')
    ]
    JOB_STATUS = [
        ('Open', 'Open'),
        ('Closed', 'Closed'),
        ('Deleted', 'Deleted')
    ]
    JOB_LEVEL = [
        ('Unspecified', 'Unspecified'),
        ('Entry', 'Entry'),
        ('Mid', 'Mid'),
        ('Senior', 'Senior')
    ]
    DURATION = [
        ('Days', 'Days'),
        ('Weeks', 'Weeks'),
        ('Months', 'Months'),
        ('Permanent', 'Permanent'),
    ]
    date_posted = models.DateField(null=False, blank=False, auto_now_add=True)
    posted_by = models.ForeignKey(Employer, on_delete=models.CASCADE, related_name='job_author', blank=True)
    job_title = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    description_upload = models.FileField(upload_to='documents', storage=OverwriteStorage(), null=True, blank=True)
    status = models.CharField(max_length=15, choices=JOB_STATUS, default='Open')
    date_closed = models.DateField(null=True, blank=True)
    location = models.CharField(max_length=100, choices=LOCATION_CHOICES)
    job_type_id = models.ForeignKey(JobType, on_delete=models.CASCADE, related_name='job_type')
    industry_id = models.ForeignKey(Industry, on_delete=models.CASCADE, related_name='job_industry')
    job_level = models.CharField(max_length=15, choices=JOB_LEVEL, null=True, blank=True, default='Unspecified')
    duration_type = models.CharField(max_length=10, choices=DURATION)
    duration = models.IntegerField(null=True, blank=True, validators=[MinValueValidator(1)])
    salary_min = models.DecimalField(null=True, blank=True, max_digits=8, decimal_places=2, validators=[MinValueValidator(0.00)])
    salary_max = models.DecimalField(null=True, blank=True, max_digits=8, decimal_places=2, validators=[MinValueValidator(0.00)])
    skills = models.ManyToManyField(Skill, related_name='job_skills')
    available_positions = models.PositiveIntegerField(null=True, blank=True, default=1, validators=[MinValueValidator(1)])
    is_active = models.CharField(blank=True, max_length=10, choices=STATUS_CHOICES, default=STATUS_CHOICES[2][1])
    other_skills = models.TextField(null=True, blank=True)

    def __str__(self):
        title = self.job_title
        return title

    def __iter__(self):
        return [
            self.job_title,
            self.location,
            self.duration,
            self.duration_type,
            self.salary_min,
            self.salary_max,
            self.skills
        ]

    class Meta:
        get_latest_by = 'date_posted'


class HelpDeskComplaints(models.Model):
    user_no = models.ForeignKey(User, on_delete=models.CASCADE, related_name='complainant')
    subject = models.CharField(max_length=100)
    details = models.TextField()
    admin_id = models.ForeignKey(Admin, on_delete=models.CASCADE, related_name='assigned_admin')


# User notifications.
class UserNotifications(models.Model):
    to_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='to_user')
    from_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='from_user')
    notification = models.TextField()
    type = models.CharField(max_length=100)
    to_show = models.BooleanField(default=True)
    date_time = models.DateTimeField(default=datetime.now)


class EmailThread(threading.Thread):
    def __init__(self, subject, html_content, recipient_list):
        self.subject = subject
        self.recipient_list = recipient_list
        self.html_content = html_content
        threading.Thread.__init__(self)

    def run(self):
        msg = EmailMessage(self.subject, self.html_content, EMAIL_HOST_USER, self.recipient_list)
        msg.content_subtype = "html"
        msg.send()


def send_html_mail(subject, html_content, recipient_list):
    EmailThread(subject, html_content, recipient_list).start()

Admin/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from upload_validator import FileTypeValidator

from .models import Admin
from Home.models import Job, JobType, Major, Skill, Industry
from Alumni.models import Alumni
from Student.models import Student
from Employer.models import Employer

import dns.resolver, dns.exception


class InitialAdminForm(forms.ModelForm):
    first_name = forms.CharField(label='First Name')
    last_name = forms.CharField(label='Last Name')
    email = forms.EmailField(label='Email Address', required=True)
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user = super(InitialAdminForm, self).save(commit=False)
        user.username = self.cleaned_data["email"]
        user.set_password(self.cleaned_data["password1"])
        user.is_staff = True
        if commit:
            user.save()
        content_type = [ContentType.objects.get_for_model(Industry), ContentType.objects.get_for_model(JobType),
                        ContentType.objects.get_for_model(Job), ContentType.objects.get_for_model(Major),
                        ContentType.objects.get_for_model(Skill), ContentType.objects.get_for_model(Employer),
                        ContentType.objects.get_for_model(Student), ContentType.objects.get_for_model(Alumni)]
        permissions = Permission.objects.filter(content_type__in=content_type)  # 14 industry, #15 jobtype, #16 skill, #18 job
        user.user_permissions.add(*permissions)
        return user

    def usernameExists(self):
        email = self.cleaned_data.get("email")
        if User.objects.filter(username=email).exists():
            return True
        return False

    def emailExists(self):
        email = self.cleaned_data.get("email")
        if User.objects.filter(email=email).exists():
            return True
        return False

    def emailDomainExists(self):
        email = self.cleaned_data.get("email")
        domain = email.split('@')[1]
        try:
            dns.resolver.query(domain, 'MX')
            return True

        except dns.exception.DNSException:
            return False

    def samePasswords(self):
        p1 = self.cleaned_data.get("password1")
        p2 = self.cleaned_data.get("password2")

        if p1 != p2:
            return False
        return True


class AdminForm(forms.ModelForm):
    gender_choices = [
        ('Male', 'Male'),
        ('Female', 'Female')
    ]
    gender = forms.ChoiceField(choices=gender_choices, widget=forms.Select(attrs={'class': 'custom-select'}))

    dp = forms.ImageField(label='Select a profile picture (only jpeg and png file formats allowed)', required=False,
                          validators=[FileTypeValidator(
                              allowed_types=['image/jpeg', 'image/png']
                          )])

    class Meta:
        model = Admin
        exclude = ['user', ]


class EditAdminProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name'
        )
        labels = (
            {'first_name': 'First Name'},
            {'last_name': 'Last Name'}
        )
        exclude = ['email', 'password1', 'password2']


class AddIndustryForm(forms.ModelForm):
    industry_name = forms.CharField(max_length=50, required=True, widget=forms.TextInput(attrs=
                                                                                         {'class': 'form-control-text',
                                                                                          'style': 'resize:none;'}))


class Statistics(forms.Form):
    start_date = forms.DateField(widget=forms.TextInput(attrs={'type': 'date', 'id':'start_date'}), required=True)
    end_date = forms.DateField(widget=forms.TextInput(attrs={'type': 'date', 'id':'end_date'}), required=True)


class JobStats(forms.ModelForm):
    LOCATION_CHOICES = [
        ('--Select--', '--Select--'),
        ('Abu Dhabi', 'Abu Dhabi'),
        ('Dubai', 'Dubai'),
        ('Sharjah', 'Sharjah'),
        ('Umm al-Qaiwain', 'Umm al-Qaiwain'),
        ('Fujairah', 'Fujairah'),
        ('Ajman', 'Ajman'),
        ('Ra’s al-Khaimah', 'Ra’s al-Khaimah')
    ]
    start_date = forms.DateField(widget=forms.TextInput(attrs={'type': 'date', 'id':'start_date'}), required=True)
    end_date = forms.DateField(widget=forms.TextInput(attrs={'type': 'date', 'id':'end_date'}), required=True)
    industry = forms.ModelMultipleChoiceField(
        widget=forms.CheckboxSelectMultiple(),
        queryset=Industry.objects.all().order_by('industry_name'),
        required=False,
        label="Industry"
    )
    job_type = forms.ModelChoiceField(
        widget=forms.Select(),
        queryset=JobType.objects.all(),
        required=False,
        label="Job Type"
    )
    location = forms.CharField(max_length=100, required=False, widget=forms.Select(choices=LOCATION_CHOICES))

    class Meta:
        model = Job
        fields = ['industry_id', 'job_type_id', 'location']

    def __init__(self, *args, **kwargs):
        super(JobStats, self).__init__(*args, **kwargs)
        self.fields['job_type'].required = False
        self.fields['industry'].required = False

class StudentStats(forms.Form):
    start_date = forms.DateField(widget=forms.TextInput(attrs={'type': 'date', 'id':'start_date'}), required=True)
    end_date = forms.DateField(widget=forms.TextInput(attrs={'type': 'date', 'id':'end_date'}), required=True)
    major = forms.ModelMultipleChoiceField(
        widget=forms.CheckboxSelectMultiple(),
        queryset=Major.objects.all().order_by('major_name'),
        required=False,
        label="Major"
    )
    skill = forms.ModelMultipleChoiceField(
        widget=forms.CheckboxSelectMultiple(),
        queryset=Skill.objects.all().order_by('skill_name'),
        required=False,
        label="Skills"
    )

Home/templates/Home/alumni_details.html
{% extends "theme.html" %}
{% load staticfiles %}

<!-- Stylesheet -->
{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/Profile.css' %}"/>
{% endblock %}

{% block title %}
    Alumni Details - Murdoch Dubai Career Portal
{% endblock %}

{% block content %}
    {% csrf_token %}
    <div id="profileBody">
        <div class="row py-2">
            <div class="icon col-md-6 col-xs-12 text-md-right text-center">
                {% if alumni.dp %}
                    <img src="{{ alumni.dp.url }}" height="300.0rem" width="300.0rem"><br>
                {% else %}
                    <img src="{% static 'DefaultDP.jpg' %}" height="300.0rem" width="300.0rem"><br>
                {% endif %}
            </div>
            <div class="student-profile col-md-6 col-xs-12 text-left py-2">
                <h3>{{ alumni.user.first_name }} {{ alumni.user.last_name }} - Alumni </h3>
                <p><b>Email:</b> {{ alumni.user }}</p>
                <p><b>Gender:</b> {{ alumni.gender }}</p>
                <p><b>Date of Birth:</b> {{ alumni.date_of_birth|date:"d M Y" }}</p>
                {% if obj.student_id %}
                    {{ obj.student_id.label }}
                    {{ obj.student_id }}
                {% endif %}
                <b>Skills</b>
                {% for skill in alumni.skills.all %}
                    <li>{{ skill }}</li>
                {% endfor %}
                <br>
                <b>Majors</b>
                {% for major in alumni.majors.all %}
                    <li>{{ major }}</li>
                {% endfor %}
            </div>
        </div><!-- End of row -->
        <div class="text-center">
            {% if user_type == 'admin' %}
            <a  class="text-decoration-none text-white" href="{% url 'admin_edit_alumni_profile' alumni.user_id %}">
                <button type="submit" class="btn btn-primary">Edit Profile</button>
            </a>
            {% endif %}
            <a class="text-decoration-none text-white" href="{% url 'get_alumni_cv_file' alumni.user_id %}">
                <button type="button" class="btn btn-primary">Download CV</button>
            </a>
        </div>
    </div>
{% endblock %}

Home/templates/Home/anti_scam.html
{% extends "theme.html" %}
{% load staticfiles %}

<!-- Additional Stylesheets -->
{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/AboutUs.css' %}"/>
{% endblock %}

{% block title %}
    Anti-Scam - Murdoch Dubai Career Portal
{% endblock %}

{% csrf_token %}

{% block content %}
    <div class="col-12">
        <h1 class="text-center"><u>Anti-Scam</u></h1>
        <br>
        <h3>Help Protect yourself against Internet fraud!</h3>
        <p>The vast majority of ads are posted by honest people and trust. So you can do excellent business. Despite
            this, it is important to follow a few common sense rules following to prevent any attempt to scam.</p>
        <br>
        <h3>Our advice</h3>
        <ol>
            <li>Do business with people you can meet in person.</li>
            <li>Never send money through Western Union, MoneyGram or other anonymous payment systems.</li>
            <li>Never send money or products abroad.</li>
            <li>Do not accept checks.</li>
            <li>Ask about the person you're dealing with another confirming source name, address and telephone number.</li>
            <li>Keep copies of all correspondence (emails, ads, letters, etc.) and details of the person.</li>
            <li>If a deal seems too good to be true, there is every chance that this is the case. Refrain.</li>
        </ol>
        <br>
        <h3>Recognize attempted scam</h3>
        <ol>
            <li>The majority of scams have one or more of these characteristics:</li>
            <li>The person is abroad or traveling abroad.</li>
            <li>The person refuses to meet you in person.</li>
            <li>Payment is made through Western Union, Money Gram or check.</li>
            <li>The messages are in broken language (English or French or ...).</li>
            <li>The texts seem to be copied and pasted.</li>
            <li>The deal seems to be too good to be true.</li>
        </ol>
        <br>
    </div>
{% endblock %}

Home/templates/Home/close_job.html
{% extends "theme.html" %}
{% load staticfiles %}

{% block title %}
    Close Jobs - Murdoch Dubai Career Portal
{% endblock %}

{% block stylesheets %}
    <script src="{% static 'js/closeJobs.js' %}" type="text/javascript"></script>
{% endblock %}

{% block content %}
<div>
    <form method='POST' onsubmit="return validate(this)">
        {% csrf_token %}
        <h2 class="text-center">Are you sure you want to close the job {{ job.job_title }}?</h2>
        <h3 class="text-center">Did a Murdoch Student get this job?</h3>
        <div class="text-center">
            <input type='radio' name='isMurdochStd' value='yes' id='yes' required> Yes
            <input type='radio' name='isMurdochStd' value='no' id='no' required> No<br>
            <br><br>
            <button class="btn btn-primary" type="submit" onsubmit="return validate(this)">
                Close
            </button>
            <button class="btn btn-secondary" type="button">
                <a class="text-decoration-none text-white" href="{% url 'job_details' job.id %}">Cancel</a>
            </button>
        </div>
    </form>
</div>
{% endblock %}

Home/templates/Home/employer_create_jobs.html
{% extends "theme.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
<!-- Additional Stylesheet -->
{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/CreateJob.css' %}"/>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="https://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/5.5.0/tinymce.min.js"></script>
{% endblock %}

{% block title %}
    Create Job Listing - Murdoch Dubai Career Portal
{% endblock %}

{% block image %}
<div id="container">
    <img src="{% static 'images/2.png' %}" alt="Home page image">
</div>
{% endblock %}
{% block jQueryCall %}
    <script>
    $("#id_email").focusout(function (e) {
        var username = $(this).val();
        $.ajax({
                type: 'GET',
                url: "{% url 'check_student_username' %}",
                data: {"username": username},
                success: function (response) {
                    if(!response["valid"]) {
                        e.preventDefault();
                            $("#usernameError").css('color', 'red').html("This username is already being used");
                        }
                    else {
                            $("#usernameError").css('color', '').html("");
                    }
                },
                error: function (response) {
                    console.log(response);
                }
        });
        });
    </script>
    <script src="{% static 'js/ManageJob.js' %}" type="text/javascript"></script>
{% endblock %}
{% block content %}
<script>
tinymce.init({selector:'#id_description, #id_company_description',
    plugins: [
        "advlist lists anchor emoticons"
    ],
    toolbar: [
        'undo redo | bold italic subscript | indent outdent bullist numlist | anchor | emoticons'
    ],
});

function disableOthersField() {
    document.getElementById("otherskills").style.display = "none";

    var labels = document.getElementsByTagName('label');
    for (var i = 0; i < labels.length; i++) {
        if (labels[i].htmlFor === "otherskills") {
            labels[i].style.display = "none";
        }
    }
    document.getElementById("duration").disabled = document.getElementById("duration_type").value === "Permanent";
}

function checkOtherSkills(elem) {
    if(elem.value == {{ others_id }}) {
        var labels = document.getElementsByTagName('label');
        for (var i = 0; i < labels.length; i++) {
            if (labels[i].htmlFor === "otherskills") {
                if(elem.checked) {
                    document.getElementById("otherskills").style.display = "block";
                    labels[i].style.display = "block";
                }
                else {
                    document.getElementById("otherskills").style.display = "none";
                    labels[i].style.display = "none";
                }
            }
        }
    }
}

function searchSkill() {
    var input = document.getElementById('myInput');
    var filter = input.value.toUpperCase();
    var ul = document.getElementById("skills");
    var li = ul.getElementsByTagName("li");

    for(var i=0; i<li.length; i++) {
        if(li[i].innerText.toUpperCase().indexOf(filter) > -1) {
          li[i].style.display = "";
        } else {
          li[i].style.display = "none";
        }

        {% if user_type == 'admin' %}
            if(li[i].innerText.indexOf("Others") > -1) {
              li[i].style.display = "none";
            }
        {% endif %}
    }
}

function removeOtherSkill() {
    var ul = document.getElementById("skills");
    var li = ul.getElementsByTagName("li");

    for(var i=0; i<li.length; i++) {
        if(li[i].innerText.indexOf("Others") > -1) {
          li[i].style.display = "none";
        }
    }
    document.getElementById("duration").disabled = document.getElementById("duration_type").value === "Permanent";
}

function toggleDuration(elem) {
    document.getElementById("duration").disabled = elem.value === "Permanent";
}
</script>

{% if user_type == 'employer' %}
    <body onload="disableOthersField()">
{% elif user_type == 'admin' %}
    <body onload="removeOtherSkill()">
{% endif %}

<div id="createJobBody">
    <h2 class="text-center">Create Job Listing</h2>
    <hr>
    <form action="create_job" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% if user_type == 'employer' %}
            <div>{{ form.job_title|as_crispy_field }}</div>
            <div>{{ form.description|as_crispy_field }}</div>
            <div>{{ form.description_upload|as_crispy_field }}</div>
            <div>{{ form.location|as_crispy_field }}</div>
            <div class="form-row">
                <div class="form-group col-md-6 col-sm-6 col-xs-12">{{ form.job_type_id|as_crispy_field }}</div>
                <div class="form-group col-md-6 col-sm-6 col-xs-12">{{ form.industry_id|as_crispy_field }}</div>
            </div>
            <div>{{ form.job_level|as_crispy_field }}</div>
            <div class="form-row">
                <div class="form-group col-md-6 col-sm-6 col-xs-12">{{ form.duration_type|as_crispy_field }}</div>
                <div class="form-group col-md-6 col-sm-6 col-xs-12">{{ form.duration|as_crispy_field }}</div>
            </div>
            <div>{{ form.available_positions|as_crispy_field }}</div>
            <div class="form-row">
                <div class="form-group col-md-6 col-sm-6 col-xs-12">{{ form.salary_min|as_crispy_field }}</div>
                <div class="form-group col-md-6 col-sm-6 col-xs-12">{{ form.salary_max|as_crispy_field }}</div>
            </div>
            <div class="form-row">
                <div id="minError" class="form-group col-6"></div>
                <div id="maxError" class="form-group col-6"></div>
            </div>
            {{ form.skills.label }}
            <div class="skills-container">
                <input class="searchTerm form-control" type="text" id="myInput" onkeyup="searchSkill()" placeholder="Search for skills...">
                {{ form.skills }}
            </div>
            <small>Select 'Others' to enter additional skills</small><br><br>
            <div>{{ form.other_skills|as_crispy_field }}</div>
        {% elif user_type == 'admin' %}
            <div>{{ jobForm.job_title|as_crispy_field }}</div>
            <div>{{ jobForm.description|as_crispy_field }}</div>
            <div>{{ jobForm.description_upload|as_crispy_field }}</div>
            <div>{{ jobForm.location|as_crispy_field }}</div>
            <div class="form-row">
                <div class="form-group col-6">{{ jobForm.job_type_id|as_crispy_field }}</div>
                <div class="form-group col-6">{{ jobForm.industry_id|as_crispy_field }}</div>
            </div>
            <div>{{ jobForm.job_level|as_crispy_field }}</div>
            <div class="form-row">
                <div class="form-group col-6">{{ jobForm.duration_type|as_crispy_field }}</div>
                <div class="form-group col-6">{{ jobForm.duration|as_crispy_field }}</div>
            </div>
            <div>{{ jobForm.available_positions|as_crispy_field }}</div>
            <div class="form-row">
                <div class="form-group col-6">{{ jobForm.salary_min|as_crispy_field }}</div>
                <div class="form-group col-6">{{ jobForm.salary_max|as_crispy_field }}</div>
            </div>
            <div class="form-row">
                <div id="minError" class="form-group col-6"></div>
                <div id="maxError" class="form-group col-6"></div>
            </div>
            {{ jobForm.skills.label }}
            <div class="skills-container">
                <input class="searchTerm form-control" type="text" id="myInput" onkeyup="searchSkill()" placeholder="Search for skills...">
                {{ jobForm.skills }}
            </div>
            <br><hr><br>
            <div>{{ employerForm.email|as_crispy_field }}</div>
            <div id="usernameError"></div>
            <div class="form-row">
                <div class="form-group col-6">{{ employerForm.password1|as_crispy_field }}</div>
                <div class="form-group col-6">{{ employerForm.password2|as_crispy_field }}</div>
            </div>
            <br><hr><br>
            <div>{{ companyForm.company_name|as_crispy_field }}</div>
            <div>{{ companyForm.company_description|as_crispy_field }}</div>
            <div>{{ companyForm.company_website|as_crispy_field }}</div>
            <div>{{ companyForm.contact_name|as_crispy_field }}</div>
            <div>{{ companyForm.phone_number|as_crispy_field }}</div>
            <div>{{ companyForm.logo|as_crispy_field }}</div>
            <div>{{ companyForm.trade_license|as_crispy_field }}</div>
        {% endif %}
        <div class="text-center">
            <button class="btn btn-primary" type="submit">
                Submit
            </button>
            <button class="btn btn-secondary" type="button">
                <a class="text-decoration-none text-white" href="/">Cancel</a>
            </button>
        </div>
    </form>
</div>
</body>
{% endblock %}