DjangoUnlimited/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from rest_framework import routers

from Admin.views import download_file

router = routers.SimpleRouter()

urlpatterns = [
    path('', include('Home.urls')),
    path('admin/backups/', include('dbbackup_ui.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('Accounts.urls')),
    path('alumni/', include('Alumni.urls')),
    path('my_admin/', include('Admin.urls')),
    path('student/', include('Student.urls')),
    path('employer/', include('Employer.urls')),
    path('HelpDesk/', include('HelpDesk.urls')),
    path('bulletin/', include('Bulletin.urls')),  # Using URLS from the Bulletin app
    path('backup/<str:filename>', download_file, name="backup_download"),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
                            static(settings.BACKUP_URL, document_root=settings.BACKUP_ROOT)

Employer/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('employer_registration', views.signup, name='employer_register'),
    path('edit_employer_profile', views.edit_profile, name='edit_employer_profile'),
    path('view_employer_profile', views.view_profile, name='view_employer_profile'),
    path('validate_username', views.check_username, name="check_employer_username"),
    path('activate', views.activate, name='activate'),
    path('get_employer_trade_license/<int:id>', views.get_employer_trade_license, name='get_employer_trade_license'),
]

Home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('create_job', views.create_job, name='create_job'),
    path('view_jobs', views.view_jobs, name='view_jobs'),
    path('my_applications', views.my_applications, name='my_applications'),
    path('job_details/<int:id>', views.job_details, name='job_details'),
    path('edit_job/<int:id>', views.edit_job, name='edit_job'),
    path('delete_job/<int:id>', views.delete_job, name='delete_job'),
    path('close_job/<int:id>', views.close_job, name='close_job'),
    path('reopen_job/<int:id>', views.reopen_job, name='reopen_job'),
    path('view_students', views.view_students, name='view_students'),
    path('view_alumni', views.view_alumni, name='view_alumni'),
    path('student_details/<int:id>', views.student_details, name='student_details'),
    path('alumni_details/<int:id>', views.alumni_details, name='alumni_details'),
    path('job_to_student_skills/<int:id>', views.job_to_student_skills, name='job_to_student_skills'),
    path('job_to_alumni_skills/<int:id>', views.job_to_alumni_skills, name='job_to_alumni_skills'),
    path('get_job_description_file/<int:id>', views.get_job_description_file, name='get_job_description_file'),
    path('get_student_cv_file/<int:id>', views.get_student_cv_file, name='get_student_cv_file'),
    path('get_alumni_cv_file/<int:id>', views.get_alumni_cv_file, name='get_alumni_cv_file'),
    path('terms', views.terms, name='terms'),
    path('faq', views.faq, name='faq'),
    path('anti_scam', views.anti_scam, name='anti_scam'),
    path('privacy', views.privacy, name='privacy'),
    path('sitemap', views.sitemap, name='sitemap'),
]

Employer/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from datetime import datetime
from django.core.validators import RegexValidator

from django.db.models.signals import post_save
from django.dispatch import receiver


class Employer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, related_name='employer_user')
    STATUS_CHOICES = [
        ('Accepted', 'Accepted'),
        ('Rejected', 'Rejected'),
        ('Pending', 'Pending')
    ]
    company_name = models.CharField(max_length=50)
    company_description = models.TextField(null=True, blank=True)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                 message="Phone number must be entered in the format: '+999999999' or all numbers. Up to 15 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=False)
    logo = models.ImageField(upload_to='company_logos', null=True, blank=True)
    contact_name = models.CharField(max_length=50, blank=False, default='N/A')
    trade_license = models.FileField(upload_to='trade_licenses', null=True, blank=True)
    company_website = models.URLField(blank=True)
    is_active = models.CharField(blank=True, max_length=10, choices=STATUS_CHOICES, default=STATUS_CHOICES[2][1])

    def __str__(self):
        name = self.user.__str__()
        return name

Employer/forms.py
import dns.exception
import dns.resolver
from django import forms
from django.contrib.auth.models import User
from upload_validator import FileTypeValidator

from .models import Employer


class InitialEmployerForm(forms.ModelForm):
    email = forms.EmailField(label='Email Address', required=True)
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput,
                                help_text="The password must be 8 characters or more, and must have at least 1 "
                                          "numeric character and 1 letter.")
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = (
            'email',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user = super(InitialEmployerForm, self).save(commit=False)
        user.username = self.cleaned_data["email"]
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

    def usernameExists(self):
        email = self.cleaned_data.get("email")
        if User.objects.filter(username=email).exists():
            return True
        return False

    def emailExists(self):
        email = self.cleaned_data.get("email")
        if User.objects.filter(email=email).exists():
            return True
        return False

    def emailDomainExists(self):
        email = self.cleaned_data.get("email")
        domain = email.split('@')[1]
        try:
            dns.resolver.query(domain, 'MX')
            return True

        except dns.exception.DNSException:
            return False

    def samePasswords(self):
        p1 = self.cleaned_data.get("password1")
        p2 = self.cleaned_data.get("password2")

        if p1 != p2:
            return False
        return True


class EmployerForm(forms.ModelForm):
    logo = forms.ImageField(label='Logo', required=False, help_text="Only jpeg or png file formats allowed.",
                            validators=[FileTypeValidator(
                                allowed_types=['image/jpeg', 'image/png']
                            )])
    company_name = forms.CharField(max_length=50, label='Company Name', required=True, widget=forms.TextInput(
        attrs={'class': 'form-control-text', 'style': 'resize:none;'}))
    company_description = forms.CharField(label='Company Description', required=False, widget=forms.Textarea)
    company_website = forms.URLField(label='Company Website', required=True,
                                     help_text="The website should start with http or https.")
    phone_number = forms.CharField(label="Contact Number", required=True, max_length=15, min_length=9,
                                   help_text="The contact number should be a minimum 9  and must be appended by a plus symbol followed by the country code extension",
                                   widget=forms.TextInput(
                                       attrs={'class': 'form-control-text', 'style': 'resize:none;'}), )
    contact_name = forms.CharField(max_length=50, label='Contact Name', required=True, widget=forms.TextInput(
        attrs={'class': 'form-control-text', 'style': 'resize:none;'}))
    trade_license = forms.FileField(allow_empty_file=False, label='Trade License', required=False,
                                    help_text="Please attach a copy of your registered trade license",
                                    validators=[FileTypeValidator(
                                        allowed_types=["image/*", "application/pdf", "application/msword",
                                                       "application/vnd.openxmlformats-officedocument.wordprocessingml.document"]
                                    )])

    class Meta:
        model = Employer
        exclude = ['user', 'employer_id', 'is_active']


class EditEmployerForm(forms.ModelForm):
    logo = forms.ImageField(label='Logo', required=False, help_text="Only jpeg or png file formats are allowed.",
                            validators=[FileTypeValidator(
                                allowed_types=['image/jpeg', 'image/png']
                            )])
    company_name = forms.CharField(max_length=50, label='Company Name', required=True, widget=forms.TextInput(
        attrs={'class': 'form-control-text', 'style': 'resize:none;'}))
    company_description = forms.CharField(label='Company Description', required=False, widget=forms.Textarea)
    company_website = forms.URLField(label='Company Website', required=True,
                                     help_text="Website should start with http or https")
    phone_number = forms.CharField(label="Contact Number", required=True, max_length=15,
                                   help_text="Phone number should be minimum 9 and maximum 15 digits with no spaces or - characters",
                                   widget=forms.TextInput(
                                       attrs={'class': 'form-control-text', 'style': 'resize:none;'}))
    contact_name = forms.CharField(max_length=50, label='Contact Name', required=True, widget=forms.TextInput(
        attrs={'class': 'form-control-text', 'style': 'resize:none;'}))
    trade_license = forms.FileField(allow_empty_file=False, label='Trade License', required=False,
                                    help_text="Please attach a copy of your registered trade license",
                                    validators=[FileTypeValidator(
                                        allowed_types=["image/*", "application/pdf", "application/msword",
                                                       "application/vnd.openxmlformats-officedocument.wordprocessingml.document"]
                                    )])

    class Meta:
        model = Employer
        exclude = ['user', 'employer_id', 'is_active']


class EmployerAccVerificationForm(forms.ModelForm):
    class Meta:
        model = Employer
        fields = ['user', 'is_active']

Employer/templates/Employer/edit_employer_profile.html
{% extends "theme.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

<!-- Additional Stylesheets -->
{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/Profile.css' %}"/>
    <script src="{% static 'js/EditProfile.js' %}" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/5.5.0/tinymce.min.js"></script>
{% endblock %}

<script>
    tinymce.init({selector:'#id_company_description',
        plugins: [
        "advlist lists anchor emoticons"
        ],
        toolbar: [
            'undo redo | bold italic subscript | indent outdent bullist numlist | anchor | emoticons'
        ],
    });
</script>

{% block title %}
    Edit Profile - Murdoch Dubai Career Portal
{% endblock %}

{% block content %}
    {% if form.errors %}
        <p>There are errors</p>
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
    {% endif %}
    <div id="editProfileBody">
        <h1 class="text-center">Edit Profile</h1>
        <div class="col-12">
        {% if user_type == 'employer' %}
            <form method="post" enctype="multipart/form-data" action="edit_employer_profile" onsubmit="return validatePhone()">{% csrf_token %}
                <div>{{ employer_form.company_name|as_crispy_field }}</div>
                <div>{{ employer_form.company_description|as_crispy_field }}</div>
                <div>{{ employer_form.company_website|as_crispy_field }}</div>
                <div>{{ employer_form.contact_name|as_crispy_field }}</div>
                <div>{{ employer_form.phone_number|as_crispy_field }}</div>
                <div>{{ employer_form.logo|as_crispy_field }}</div>
                <div>{{ employer_form.trade_license|as_crispy_field }}</div>
                <div class="text-center">
                    <button class="btn btn-primary" type="submit">
                        Save Changes
                    </button>

                    <a class="text-decoration-none text-white" href="view_employer_profile">
                        <button class="btn btn-secondary" type="button">Cancel</button>
                    </a>
                </div>
            </form>
        {% else %}
            <form method="post" enctype="multipart/form-data" action="{% url 'admin_edit_employer_profile' obj.user_id %}" onsubmit="return validatePhone()">{% csrf_token %}
                {% for field in employer_form %}
                    <div>{{ field|as_crispy_field }}</div>
                {% endfor %}
                <div class="text-center">
                    <button class="btn btn-primary" type="submit">
                        Save Changes
                    </button>

                    <a class="text-decoration-none text-white" href="{% url 'view_account_details' obj.user_id %}">
                        <button class="btn btn-secondary" type="button">Cancel</button>
                    </a>
                </div>
            </form>
        {% endif %}
        </div>
    </div>
{% endblock %}

Employer/templates/Employer/employer_registration.html
{% extends "theme.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

<!-- Additional Stylesheet -->
{% block stylesheets %}
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="https://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/5.5.0/tinymce.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/Register.css' %}"/>
{% endblock %}
{% block jQueryCall %}
        <script src="{% static 'js/EmployerRegistration.js' %}" type="text/javascript"></script>
        <script>
        tinymce.init({selector:'#id_company_description',
            plugins: [
        "advlist lists anchor emoticons"
    ],
    toolbar: [
        'undo redo | bold italic subscript | indent outdent bullist numlist | anchor | emoticons'
    ],
        });

        $("#id_email").focusout(function (e) {
              e.preventDefault();
              var username = $(this).val();
              $.ajax({
                    type: 'GET',
                    url: "{% url 'check_student_username' %}",
                    data: {"username": username},
                    success: function (response) {
                          if(!response["valid"]) {
                                $("#usernameError").css('color', 'red').html("This username is already being used");
                            }
                          else {
                                $("#usernameError").css('color', '').html("");
                          }
                    },
                    error: function (response) {
                          console.log(response);
                    }
              });
            });
        </script>
{% endblock %}

{% block title %}
    Employer Account Signup - Murdoch Dubai Career Portal
{% endblock %}

{% block content %}
<div id="form" class="row justify-content-center align-items-center">
    <div class="col-12">
        <h2 class="text-center">Employer Registration</h2>
        <hr>
        <form id="companyForm" action="employer_registration" method="post" enctype="multipart/form-data">{% csrf_token %}
            {{ user_form.email|as_crispy_field }}
            <div id="emailError"></div>
            <div id="usernameError"></div>
            <div class="form-row">
                <div class="form-group col-md-6 col-sm-6 col-xs-12">{{ user_form.password1|as_crispy_field }}</div>
                <div class="form-group col-md-6 col-sm-6 col-xs-12">{{ user_form.password2|as_crispy_field }}</div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6 col-sm-6 col-xs-12"  id="password1Error"></div>
                <div class="form-group col-md-6 col-sm-6 col-xs-12"  id="password2Error"></div>
            </div>
            <div>{{ employer_form.company_name|as_crispy_field }}</div>
            <div>{{ employer_form.company_description|as_crispy_field }}</div>
            <div>{{ employer_form.company_website|as_crispy_field }}</div>
            <div>{{ employer_form.contact_name|as_crispy_field }}</div>
            <div>{{ employer_form.phone_number|as_crispy_field }}</div>
            <div>{{ employer_form.logo|as_crispy_field }}</div>
            <div>{{ employer_form.trade_license|as_crispy_field }}</div>

            <div id="register" class="text-center">
                <button class="btn btn-danger" type="submit">Register</button>
            </div><!-- End of register -->
        </form>
    </div><!-- End of col -->
</div><!-- End of row -->
{% endblock %}

Employer/templates/Employer/job_closing.html
{% autoescape off %}
Dear {{ first_name }},<br><br>
Thank you for using Murdoch University Dubai’s online career portal. This is an
automated message to confirm your job posting has been closed on our website. We
hope you have found a successful candidate for this position.<br>
Please contact us at careerportal@murdoch.edu.au for any queries.<br><br>
Kind regards,<br>
The Murdoch University Dubai Team
{% endautoescape %}

Employer/templates/Employer/job_deletion.html
{% autoescape off %}
Dear {{ first_name }},<br><br>
Thank you for using Murdoch University Dubai’s online career portal. This is an
automated message to confirm your job posting has been deleted from the website.<br>
Please contact us at careerportal@murdoch.edu.au for any queries.<br><br>
Kind regards,<br>
The Murdoch University Dubai Team
{% endautoescape %}

Employer/templates/Employer/job_post_request.html
{% autoescape off %}
Dear {{ first_name }},<br><br>
Thank you for using Murdoch University Dubai’s online career portal. This is an
automated message to confirm we have received your job posting and it is pending
approval from an admin. You will receive a status on your posting within 48 working
hours.<br>
Please contact us at careerportal@murdoch.edu.au for any queries.<br><br>
Kind regards,<br>
The Murdoch University Dubai Team
{% endautoescape %}

Employer/templates/Employer/job_post_resolution.html
{% autoescape off %}
Dear {{ first_name }},<br><br>
Thank you for using Murdoch University Dubai’s online career portal. This is an
automated message to confirm your job posting has been reviewed by an admin and
the request has been '{{ status }}'.<br>
Please contact us at careerportal@murdoch.edu.au for any queries.<br><br>
Kind regards,<br>
The Murdoch University Dubai Team
{% endautoescape %}

Employer/templates/Employer/pending_activation.html
{% autoescape off %}  
Hi {{ user.username }},  
Please click on the link to confirm your registration,

http://{{ domain }}{% url 'activate' uidb64=uid token=token %}  
If you think, it's not you, then just ignore this email.  
{% endautoescape %}

Employer/templates/Employer/view_employer_profile.html
{% extends "theme.html" %}
{% load staticfiles %}

<!-- Stylesheet -->
{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/Profile.css' %}"/>
{% endblock %}

{% block title %}
    View Profile - Murdoch Dubai Career Portal
{% endblock %}

{% block content %}
    <div id="profileBody">
        <h2 class="text-center">My Profile</h2><br>
        <div class="row py-2">
            <div class="icon col-md-6 text-md-right text-center">
                {% if obj.logo %}
                    <img src="{{ obj.logo.url }}" height="300.0em" width="300.0em">
                {% else %}
                    <img src="{% static 'DefaultDP.jpg' %}" height="300.0em" width="300.0em">
                {% endif %}
            </div>
            <div class="employer-profile col-md-6 text-left py-2">
                <p><strong>Company Name:</strong> {{ obj.company_name }}</p>
                <p><strong>Company Description:</strong> {{ obj.company_description|safe }}</p>
                {% if obj.trade_license %}
                    <p><strong>Trade License:</strong> <a target="_blank" href="{{ obj.trade_license.url }}">{{ obj.trade_license }}</a></p>
                {% endif %}
                <p><strong>Contact Name:</strong> {{ obj.contact_name }}</p>
                <p><strong>Contact Number:</strong> <a href="teL:{{ obj.phone_number }}">{{ obj.phone_number }}</a></p>
                {% if obj.company_website %}
                    <p><strong>Company Website:</strong> <a href="{{ obj.company_website }}" target="_blank">{{ obj.company_website }}</a></p>
                {% endif %}
            </div>
        </div>
        <div id="edit-profile" class="text-center">
            <a class="text-decoration-none text-white" href="/employer/edit_employer_profile">
                <button type="submit" class="btn btn-primary">Edit Profile</button>
            </a>
            {% if obj.trade_license %}
                <a class="text-decoration-none text-white" href="{% url 'get_employer_trade_license' obj.user_id %}">
                    <button type="button" class="btn btn-primary">Download Trade License</button>
                </a>
            {% endif %}
        </div>
    </div>
{% endblock %}